CREATE TABLE Progetti (
IdProgetto INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
Nome TEXT NOT NULL,
Descrizione TEXT NULL,
DataApertura DATETIME NULL,
DataChiusura DATETIME NULL,
Note TEXT NULL,
NomeFile TEXT NULL,
File BLOB NULL
);
